config/routes.rb
Rails.application.routes.draw do
  resources :checkins
  resources :rooms
  resources :customers
  get "/available_rooms" => "rooms#available_rooms"
  get "/checkout" => "checkins#checkout"
  get "/get_price" => "rooms#get_price"
  get "/checkout_complete" => "checkins#checkout_complete"
  get "/welcome" => "customers#welcome"

  
  root to: 'customers#welcome'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/checkin.rb
class Checkin < ApplicationRecord
  belongs_to :room
  belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates_presence_of :first_name
  validates_presence_of :last_name

  def name
    first_name + ' ' + last_name
  end
end

app/models/room.rb
class Room < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/checkins_controller.rb
class CheckinsController < ApplicationController
  include RoomsHelper
  before_action :set_checkin, only: [:show, :edit, :update, :destroy]

  # GET /checkins
  # GET /checkins.json
  def index
    @checkins = Checkin.all
  end

  # GET /checkins/1
  # GET /checkins/1.json
  def show
  end

  # GET /checkins/new
  def new
    @checkin = Checkin.new(customer_id: params[:customer_id])
    @rooms = available_rooms
  end

  # GET /checkins/1/edit
  def edit
  end

  # POST /checkins
  # POST /checkins.json
  def create
    params[:checkindate] = DateTime.now
    @checkin = Checkin.new(checkin_params)

    respond_to do |format|
      if @checkin.save
        format.html { redirect_to customers_path, notice: 'Checkin was successfully created.' }
        @checkin.update(checked_in: true)
        @checkin.room.update(availability: false)

      else
        format.html { render :new }
        format.json { render json: @checkin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /checkins/1
  # PATCH/PUT /checkins/1.json
  def update
    respond_to do |format|
      if @checkin.update(checkin_params)
        format.html { redirect_to @checkin, notice: 'Checkin was successfully updated.' }
        format.json { render :show, status: :ok, location: @checkin }
      else
        format.html { render :edit }
        format.json { render json: @checkin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /checkins/1
  # DELETE /checkins/1.json
  def destroy
    @checkin.destroy
    respond_to do |format|
      format.html { redirect_to checkins_url, notice: 'Checkin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def checkout
    @checkin_record = Checkin.where(customer_id: params[:customer_id], checked_in: true).first
    no_of_days = DateTime.now.to_date.mjd - @checkin_record.checkindate.to_date.mjd
    @amount_to_be_paid = @checkin_record.room.price * no_of_days
  end

  def checkout_complete
    @checkin_record = Checkin.where(customer_id: params[:customer_id], checked_in: true).first
    @checkin_record.update(checked_in: false)
    @checkin_record.room.update(availability: true)
    respond_to do |format|
      format.html { redirect_to customers_path, notice: 'Checkout was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_checkin
      @checkin = Checkin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def checkin_params
      params.require(:checkin).permit(:checkindate, :checkoutdate, :room_id, :customer_id, :amount_to_be_paid, :checked_in)
    end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  def welcome
  end
  
  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_params
      params.require(:customer).permit(:first_name, :last_name, :age, :sex, :address, :mobile, :email, :birthdate)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  include RoomsHelper
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:room_no, :name, :type, :facilities, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkins_helper.rb
module CheckinsHelper
  def amount_to_be_paid()

  end
end

app/helpers/customers_helper.rb
module CustomersHelper
  def checkin_record(customer)
    checkin_record = Checkin.where(customer_id: customer.id)
    if checkin_record.present?
      if checkin_record.collect(&:checked_in).last.eql?(true)
        false
      else
        true
      end
    else
      true
    end
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
  def available_rooms
    @available_rooms = Room.where(availability: true)
  end

  def get_price
    price = Room.find(params[:room_id]).price
    # price = Room.find_by(room_type: params[:room_type]).price
    render json: { price: price, success: true }, status: 200
  end
end

app/views/checkins/_form.html.erb
<%= form_with(model: checkin, remote: true) do |form| %>
  <% if checkin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(checkin.errors.count, "error") %> prohibited this checkin from being saved:</h2>

      <ul>
      <% checkin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :checkindate %>
    <%= form.date_select :checkindate, value: Time.now, required: true %>
  </div>

  <div class="field">
    <%= form.label :room_id %>
    <%= form.collection_select :room_id, @rooms, :id, :room_type, include_blank: 'Select Room', required: true%>
  </div>

  <div class="field">
    <%= form.label :customer_id %>
    <% customer_name = Customer.find(params[:customer_id]).name%>
    <%= form.text_field :customer_id, value: params[:customer_id], required: true, readonly: true %>
  </div>

  <div class="field">
    <%= form.label 'Amount per night($)' %>
    <%= form.number_field :amount_to_be_paid, required: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

<script>
$("#checkin_room_id").on('change', function(){
  var roomId = this.value;
  $.ajax({
    url: '/get_price',
    type: 'GET',
    data: {
      room_id: roomId,
    },
    success: function(data) {
      if(data.success==true){
       document.getElementById('checkin_amount_to_be_paid').value = data.price;
       document.getElementById('checkin_amount_to_be_paid').readonly = true;

      }
    }
  });
});
</script>

app/views/checkins/checkout.html.erb
<p id="notice" style="color:#00cccc;"><%= notice %></p>

<table id = "list_rooms", class="table table-hover">

  <tr><th colspan=2> Checkin Details</th> </tr>
  <tr>
    <td>Room no.</td>
    <td><%= @checkin_record.room.room_type %></td>
  </tr>

  <tr>
    <td>Checkedin Date</td>
    <td><%= @checkin_record.checkindate.strftime("%m/%d/%Y") %></td>
  </tr>

  <tr>
    <td>Amount to be paid</td>
    <td><%= @amount_to_be_paid %></td>
  </tr>

</table>
<p>
<%= link_to '<button type="button" class="btn btn-default">Complete payment and Checkout?</button>'.html_safe, "/checkout_complete?customer_id=#{params[:customer_id]}" %>
<%= link_to '<button type="button" class="btn btn-default">Cancel</button>'.html_safe, customers_path %>
</p>

app/views/checkins/edit.html.erb
<h1>Editing Checkin</h1>

<%= render 'form', checkin: @checkin %>

<%= link_to '<button type="button" class="btn btn-default">Show</button>'.html_safe, @checkin %> | 
<%= link_to '<button type="button" class="btn btn-default">Back</button>'.html_safe, checkins_path %>

app/views/checkins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Checkins</h1>

<table>
  <thead>
    <tr>
      <th>Checkindate</th>
      <th>Room</th>
      <th>Customer</th>
      <th>Amount to be paid</th>
      <%if @checkins.present?%>
        <th colspan="3"></th>
      <%end%>
    </tr>
  </thead>

  <tbody>
    <% @checkins.each do |checkin| %>
      <tr>
        <td><%= checkin.checkindate %></td>
        <td><%= checkin.room_id %></td>
        <td><%= checkin.customer_id %></td>
        <td><%= checkin.amount_to_be_paid %></td>
        <td><%= link_to '<button type="button" class="btn btn-default">Update</button>'.html_safe, edit_checkin_path(checkin) %></td>
        <td><%= link_to '<button type="button" class="btn btn-default">Destroy</button>'.html_safe, checkin, method: :delete, data: { confirm: 'Are you sure?' } %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '<button type="button" class="btn btn-default">New Checkin</button>'.html_safe, new_checkin_path %>

app/views/checkins/new.html.erb
<h1>New Checkin</h1>

<%= render 'form', checkin: @checkin %>

<%= link_to '<button type="button" class="btn btn-default">Back</button>'.html_safe, checkins_path %>

app/views/checkins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Checkindate:</strong>
  <%= @checkin.checkindate %>
</p>

<p>
  <strong>Checkoutdate:</strong>
  <%= @checkin.checkoutdate %>
</p>

<p>
  <strong>Room:</strong>
  <%= @checkin.room %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @checkin.customer %>
</p>

<p>
  <strong>Amount to be paid:</strong>
  <%= @checkin.amount_to_be_paid %>
</p>

<%= link_to '<button type="button" class="btn btn-default">Edit</button>'.html_safe, edit_checkin_path(@checkin) %>
<%= link_to '<button type="button" class="btn btn-default">Back</button>'.html_safe, checkins_path %>

app/views/customers/_form.html.erb
<%= form_with(model: customer, local: true) do |form| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :sex %>
    <%= form.text_field :sex %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address %>
  </div>

  <div class="field">
    <%= form.label :mobile %>
    <%= form.number_field :mobile %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :birthdate %>
    <%= form.date_select :birthdate %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to '<button type="button" class="btn btn-default">Show</button>'.html_safe, @customer %>
<%= link_to '<button type="button" class="btn btn-default">Back</button>'.html_safe, customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1 style="color:#00cccc">Customers</h1>

<%= link_to '<button type="button" class="btn btn-default">Add Customer</button>'.html_safe, new_customer_path %>

  <table id = "list_customers", class="table table-hover">

  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Sex</th>
      <th>Address</th>
      <th>Mobile</th>
      <th>Email</th>
      <%if @customers.present?%>
        <th colspan="3"></th>
      <%end%>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.name %></td>
        <td><%= customer.age %></td>
        <td><%= customer.sex %></td>
        <td><%= customer.address %></td>
        <td><%= customer.mobile %></td>
        <td><%= customer.email %></td>
        <td><%= link_to '<button type="button" class="btn btn-default">Update</button>'.html_safe, edit_customer_path(customer) %></td>
        <td><%= link_to '<button type="button" class="btn btn-default">Delete</button>'.html_safe, customer, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% if checkin_record(customer).eql?(true)%>
          <td><%= link_to '<button type="button" class="btn btn-default" id="checkin_btn">Checkin</button>'.html_safe, new_checkin_path(customer_id: customer.id) %>
        <%else%>
          <td><%= link_to '<button type="button" class="btn btn-default checkout-btn" id="checkin_btn">Checkout</button>'.html_safe, "/checkout?customer_id=#{customer.id}" %>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to '<button type="button" class="btn btn-default">Back</button>'.html_safe, customers_path %>

app/views/customers/show.html.erb
<p id="notice" style="color:#00cccc;"><%= notice %></p>

<table id = "list_customers", class="table table-hover">

  <tr><th colspan=2> Customer Details</th> </tr>
  <tr>
    <td>First Name</td>
    <td><%= @customer.first_name %></td>
  </tr>

  <tr>
    <td>Last Name</td>
    <td><%= @customer.last_name %></td>
  </tr>

  <tr>
    <td>Age</td>
    <td><%= @customer.age %></td>
  </tr>

  <tr>
    <td>Sex</td>
    <td><%= @customer.sex %></td>
  </tr>

  <tr>
    <td>Address</td>
    <td><%= @customer.address %></td>
  </tr>

  <tr>
    <td>Mobile</td>
    <td><%= @customer.mobile %></td>
  </tr>

  <tr>
    <td>Email</td>
    <td><%= @customer.email %></td>
  </tr>
</table>
<p>
<%= link_to '<button type="button" class="btn btn-default">Update</button>'.html_safe, edit_customer_path(@customer) %>
<%= link_to '<button type="button" class="btn btn-default">Back</button>'.html_safe, customers_path %>
</p>

app/views/customers/welcome.html.erb
<div class="welcome">
<p class="button-div">
    <%= link_to '<button type="button" class="btn btn-default buttons">Customer Details</button>'.html_safe, customers_path %>
    <%= link_to '<button type="button" class="btn btn-default buttons">Room list</button>'.html_safe, rooms_path %>
</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotelManagement</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rooms/_form.html.erb
<%= form_with(model: room, local: true) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :room_no %>
    <%= form.number_field :room_no %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :room_type %>
    <%= form.text_field :room_type %>
  </div>

  <div class="field">
    <%= form.label :facilities %>
    <%= form.text_area :facilities %>
  </div>

  <div class="field">
    <%= form.label :price_per_night %>
    <%= form.number_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/available_rooms.html.erb
<p id="notice"><%= notice %></p>

<h1>List of available rooms</h1>

<table>
  <thead>
    <tr>
      <th>Room no</th>
      <th>Name</th>
      <th>Room Type</th>
      <th>Facilities</th>
    </tr>
  </thead>

  <tbody>
    <% @available_rooms.each do |room| %>
      <tr>
        <td><%= room.room_no %></td>
        <td><%= room.name %></td>
        <td><%= room.room_type %></td>
        <td><%= room.facilities %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to '<button type="button" class="btn btn-default">Back</button>'.html_safe, rooms_path %>

<br>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to '<button type="button" class="btn btn-default">Show</button>'.html_safe, @room %>
<%= link_to '<button type="button" class="btn btn-default">Back</button>'.html_safe, rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rooms</h1>

<%= link_to '<button type="button" class="btn btn-default">Add New Room</button>'.html_safe, new_room_path %>
<%= link_to '<button type="button" class="btn btn-default">List Available Rooms</button>'.html_safe, "/available_rooms" %>


<table>
  <thead>
    <tr>
      <th>Room no</th>
      <th>Name</th>
      <th>Room Type</th>
      <th>Facilities</th>
      <th>Price per night($)</th>
      <%if @rooms.present?%>
        <th colspan="2"></th>
      <%end%>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.room_no %></td>
        <td><%= room.name %></td>
        <td><%= room.room_type %></td>
        <td><%= room.facilities %></td>
        <td><%= "$#{room.price}" %></td>
        <td><%= link_to '<button type="button" class="btn btn-default">Update</button>'.html_safe, edit_room_path(room) %></td>
        <td><%= link_to '<button type="button" class="btn btn-default">Destroy</button>'.html_safe, room, method: :delete, data: { confirm: 'Are you sure?' } %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice" style="color:#00cccc;"><%= notice %></p>

<table id = "list_rooms", class="table table-hover">

  <tr><th colspan=2> Customer Details</th> </tr>
  <tr>
    <td>Room no.</td>
    <td><%= @room.room_no %></td>
  </tr>

  <tr>
    <td>Room Name</td>
    <td><%= @room.name %></td>
  </tr>

  <tr>
    <td>Room Type</td>
    <td><%= @room.room_type %></td>
  </tr>

  <tr>
    <td>Facilities</td>
    <td><%= @room.facilities %></td>
  </tr>

  <tr>
    <td>Price per night($)</td>
    <td><%= @room.price %></td>
  </tr>

</table>
<p>
<%= link_to '<button type="button" class="btn btn-default">Update</button>'.html_safe, edit_room_path(@room) %>
<%= link_to '<button type="button" class="btn btn-default">Back</button>'.html_safe, rooms_path %>
</p>